packages/react-centra-checkout/src/Context/index.tsx
Fixes an issue where the selection is reset after refreshing the page when running the app in development.
=> fix(CentraProvider): restore previous selection if present

packages/react-centra-checkout/src/Context/index.tsx
There is currently no way to unsubscribe a user from the newsletter. As far as I can tell this is the only [endpoint](https://docs.centra.com/swagger-ui/?api=CheckoutAPI#/6.%20customer%20handling/put_customer_update) that allows this.
This introduces some redundancy with 'updateCustomerAddress' and 'updateCustomerEmail'. Perhaps it would make more sense if there was a method solely responsible for updating the newsletter field value.
It might be that this scenario doesn't happen often enough to warrant its own method. Feel free to close this PR if that is indeed the case.
=> feat(CentraProvider): add 'updateCustomer' method

packages/create-app/createApp.js
This enables the user to see the yarn installation progress while running the npx script
fix #33
=> feat: output yarn installation progress to terminal

packages/react-centra-checkout/src/PaymentEmbed/index.tsx
Not sure if this is the best solution but this field seems to be required when making a [/payment](https://docs.centra.com/swagger-ui/?api=CheckoutAPI#/4.%20selection%20handling%2C%20checkout%20flow/post_payment) request.
=> fix(PaymentEmbed): add 'additionalPaymentProps'

packages/react-centra-checkout/src/Context/index.tsx
This attempts to solve an issue I'm having with resetting the selection when a user exits a campaign site (notably the users market). This is because the context methods use a static instance of the `ApiClient` and calling the `init` method doesn't reinitialize the necessary header.
This felt like the most flexible/reusable solution although it would also be possible to handle this in the `init` method. Either by adding an optional `reset` argument or just updating this part:
```
const clientToken = window.localStorage.getItem('checkoutToken')
if (clientToken) {
apiClient.headers.set('api-token', clientToken)
} else {
apiClient.headers.delete('api-token')
}
```
Although this would still require us to clear the `checkoutToken` from storage before calling `init`, which doesn't feel very …
=> feat(CentraContext): add 'resetSelection' method

packages/react-centra-checkout/package.json, packages/react-centra-checkout/src/Context/index.tsx, yarn.lock
This pull request changes the storage of the Centra checkout api token to a cookie instead of localStorage. This has a number of benefits:
- With a cookie, it's possible to read the token both server and client side. This means we can, for example, fetch the users selection directly on the server on the checkout and receipt pages, displaying a complete page instead of serving an empty page that is populated client side.
- Makes it possible to read the users session token in a Next.js middleware which opens up possibilities to do rewrites / redirects etc based on the token
- When searching for this topic, the general consensus seems to be storing session tokens in localStorage is not the way to go. Security is one of the reasons. While we will still have the same security concerns …
=> react-centra-checkout - Use cookie instead of localStorage for session token

packages/react-centra-checkout/src/ApiClient/index.ts
Adds ability to change options on the api client. This is useful for example on Vercel edge functions where `mode: 'cors'` is not supported.
=> feat(ApiClient): add fetch options

packages/react-centra-checkout/src/Context/index.tsx
Add support for `back-in-stock-subscription` endpoint as per Centra Checkout API documentation: https://docs.centra.com/swagger-ui/?api=CheckoutAPI#/6.%20customer%20handling/post_back_in_stock_subscription
=> add addBackInStockSubscription support

docs/src/oui/ScrollProgress.stories.js, packages/oui/src/ScrollProgress/ScrollProgress.js
Now with requestAnimationFrame for better performance and a new friction prop which adds easing.
BREAKING CHANGE: The bounds key has now been removed from the onChange callback arguments.
=> feat(ScrollProgress): add requestAnimationFrame and a new friction prop

.eslintrc.js, packages/centra-types/models/Product.d.ts, packages/centra-types/models/SelectionItem.d.ts, packages/centra-types/utils/index.d.ts, packages/react-centra-checkout/src/Context/index.tsx, yarn.lock
This PR adds:
* Overridable types to `@noaignite/centra-types`
* Type narrowing for `useCentraSelection` & `useCentraHandlers` in `@noaignite/react-centra-checkout`
=> feat: add overridable types and context type narrowing

.github/workflows/main.yml, .github/workflows/publish.yml, package.json
The CI pipeline currently breaks while running `pnpm run ci` with the following error: 
```bash
Error: app/page.tsx(1,36): error TS2307: Cannot find module '@repo/ui' or its corresponding type declarations.
```
This is caused by the execution order in the `ci` script:
```
pnpm run lint && pnpm run test && pnpm run build
```
We can't run `test` before `build`.
`test` runs `tsc` which requires that all types are accessible in the current package, which never does due to that `pnpm run build` hasn't yet executed.
=> fix(ci): `type-check` after `build`

packages/react-centra-checkout/src/Context/index.tsx, packages/react-centra-checkout/src/ShipwalletEmbed/index.tsx, packages/react-centra-checkout/src/types/global.d.ts
Fixes crash if `window.CentraCheckout` doesn't exist
=> fix(react-centra-checkout): make CentraCheckout optional

package.json
Adds flag `--no-git-checks` to release:verdaccio for quicker development and testing of packages locally (no need to commit unnecessary version changes for testing purposes).
=> chore(package.json): add --no-git-checks to verdaccio release

package.json
Revert the `ci:release` script from also executing `changeset version` to test out what the changeset-bot does.
=> build: revert ci:release script

packages/utils/src/capitalize.test.js, packages/utils/src/capitalize.ts, packages/utils/src/index.ts
* Update `capitalize` to use `default` export to follow the same pattern as the rest of the utils. Dropping `default` exports will be a future PR.
* Add `capitalize` to the index barrel file.
=> chore(capitalize): use default export and add to barrel file

.changeset/little-panthers-invite.md, packages/react-utils/package.json, packages/react-utils/tsup.config.ts
To my surprise I noticed that when consuming this package in a NextJS project the `next build` script fails for the `createRenderBlock` function meanwhile `next dev` works just fine. I'm still not entirely sure what the issue is, but I can get `next build` to succeed if I skip the `commonJS` build and only build `esm` modules.
I discussed this with @adamsoderstrom and went ahead and dropped the support for `commonJS` for this package as this package is after all meant to be consumed in an `esm` environment. Furthermore, stable `esm` support has been in `node` since version 14 and latest node version is currently at 22. Additionally it's easier to debug the built files as the `dist` folder is less bloated.
=> build(react-utils): drop commonJS support

.changeset/grumpy-suns-smoke.md, packages/react-utils/src/createSvgIcon.tsx, packages/react-utils/src/index.ts
There are many ways of working with svg's and so this helper is not intended to be the one and only solution. However, it is a handy little helper to quickly get started.
=> feat(react-utils): add new createSvgIcon helper

.changeset/rich-cups-ring.md, packages/create-app/createApp.js
This PR updates this package to match the new CIA docs. Hence, it no longer initiates a new git repo as it's meant to be created within an existing turbo git repo. Furthermore I changed the installer from using `yarn` to `pnpm` and some minor tweaks to the messages printed to the terminal.
This change is meant to adhere to the changes made in this open PR:
https://github.com/noaignite/create-ignite-app/pull/102
=> feat(create-app): switch to pnpm & no longer initiates a git repo

package.json
Adding this to enforce that the `pnpm` version is atleast 9.
Prior to this, i was able to execute `pnpm install` with version 8.
Enforcing the version won't trigger unwanted changes in
`pnpm-lock.yaml`.
=> build(package.json): add `engines.pnpm: ^9`

.changeset/swift-papayas-grin.md, packages/react-utils/package.json, packages/react-utils/tsup.config.ts, pnpm-lock.yaml
Prior to this commit, we've had an issue where directives like `"use
client"` gets stripped out of the `chunk-*` files created in the `dist`
folder, when specifying `bundle: true` in `tsup.config.ts`.
I tried to trace this issue and found a corresponding one in the `esbuild` repo (0).
In that, i found that @Seojunhwan had created a ESBuild plugin (1) that
resolves this issue. Though, as of this writing, the plugin doesn't
support single-quote directives, which we have in our repository. I
forked the repo and submitted a PR for that (2). Until then, i've
published my fix under my personal namespace and use it here.
[0]: https://github.com/evanw/esbuild/issues/3115
[1]: https://github.com/Seojunhwan/esbuild-plugin-preserve-directives
[2]: …
=> fix/react utils/bundle true

packages/utils/src/deepmerge.test.ts
Converted to TS and included some eslint/ts disables as we don't have to be as strict in test files.
No changeset needed.
=> test(utils): convert all files to ts

packages/react-centra-checkout/package.json, pnpm-lock.yaml
Update `@noaignite/*` dependency versions to `workspace:*` instead of fixed numbers as `pnpm publish` (done by Github Actions) will make sure to swap these out to the latest version upon publishing.
NOTE: No changeset needed.
=> chore(react-centra-checkout): update `@noaignite/*` package versions

.github/workflows/main.yml, .github/workflows/publish.yml, .husky/install.mjs, .husky/pre-commit, package.json, pnpm-lock.yaml
Add husky & lint-staged to run prettier on a pre-commit hook. This ensures that formatting is done for all contributors and in the same style with the locally installed prettier version in `node_modules`.
NOTE: Husky has been configured to not run on CI servers.
NOTE: No changeset needed.
=> chore(prettier): format on pre-commit hook

packages/centra-types/package.json, packages/react-centra-checkout/package.json, pnpm-lock.yaml
Bump `typescript` to version 5.4.5 matching the rest of the updated accelerator packages. Version 5.4.5 and not higher due to `@vercel/style-guide` typescript/eslint requirements. Included both these packages as `centra-types` is as dependency to `react-centra-checkout`.
NOTE: No changeset needed
=> build(centra-types, react-centra-checkout): bump typescript from 4.7.4 to 5.4.5

packages/utils/package.json, pnpm-lock.yaml
Bump `typescript` to version 5.4.5 matching the rest of the updated accelerator packages. Version 5.4.5 and not higher due to `@vercel/style-guide` typescript/eslint requirements.
=> build(utils): bump typescript from 4.7.4 to 5.4.5

packages/centra-mocks/tsup.config.ts, packages/eslint-config/react.js, packages/react-centra-checkout/package.json, packages/react-centra-checkout/src/Context/index.test.tsx, packages/react-centra-checkout/vitest.config.mts, pnpm-lock.yaml
fixes #67 
This adds unit tests to react-centra-checkout using vitest and testing-library. The mock data is taken from Centras docs, so nothing sensitive there. Very much WIP.
TODO:
=> feat(react-centra-checkout): add tests

.changeset/great-zoos-cover.md, .changeset/rude-wombats-peel.md, packages/centra-types/package.json, packages/react-centra-checkout/package.json
=> feat(centra-types, react-centra-checkout): bump minimum engine node version from 14 to 20

.changeset/config.json, CONTRIBUTING.md
As stated in ticket #249. Update changeset config to not commit. The idea is for the created changeset to be part of the same commit that implements the feature so that the linked commit in the CHANGELOG actually has all the related code.
=> chore(changeset): changeset no longer commits for you + add changeset section to CONTRIBUTING.md

.changeset/big-impalas-raise.md, packages/create-app/template-tailwind-config/tailwind.config.ts, packages/create-app/template-tailwind-config/typography.ts
Having it's own exported file for the typographic config is use if one would want to import it elsewhere. For example to create a Storybook page.
=> feat(create-app/tailwind-config): add separate exported config for typography

.github/workflows/main.yml, CONTRIBUTING.md, package.json
Tested locally by applying the changes on an ongoing PR (fails, due to lacking changeset, as it should).
I also tested it how it performs on the `main` branch by applying temporarily there as well (doesn't fail, due to being `main`).
Adding the `changeset status` call to be last in the script improves DX by seeing that the CI pipeline passes before you've necessarily submitted a changeset.
=> ci(changeset): ensure existence of changeset in PR

.changeset/nice-beers-kneel.md, .changeset/strange-boxes-fail.md, .changeset/young-suns-beam.md, packages/react-utils/src/createRenderBlock.tsx
- `blockType` is now passed to block component.
- Adapter argument `additionalData` has been renamed to `context`
- Adapter argument `context` is now always an object containing `index` & additional keys one provides to the renderer.
- Export new `BlockTypeMap` & `BlockAdapter` types.
=> feat(react-utils): pass `blockType` to block, `context` always as object & export new types

.changeset/big-beds-mate.md, packages/react-utils/src/createRenderBlock.test.tsx, packages/react-utils/src/createSvgIcon.test.tsx, packages/react-utils/src/setRef.ts, packages/react-utils/src/useEvent.ts, packages/react-utils/src/useFocusReturn.ts, packages/react-utils/src/useInert.ts, packages/react-utils/src/useIsomorphicEffect.ts, packages/react-utils/src/useSticky.ts
* fix(react-utils): add missing 'use client' directive
* test(react-utils): remove unnecessary imports
* chore(react-utils/setRef): change out deprecated MutableRefObject
=> fix(react-utils): add missing `'use client'` directive

.changeset/loud-cougars-clap.md, packages/style-guide/eslint/base.js, packages/style-guide/eslint/rules/node.js
- Global variables like `__dirname` and `process.env.` are otherwise not recognized.
- The [`eslint-config-next`](https://github.com/vercel/next.js/blob/21d2a32d50164f877917c6c79dfc0e6686a5bb59/packages/eslint-config-next/index.js#L125-L128) package already adds it
=> fix(style-guide): add `node.js` ESlint config 

.changeset/lazy-areas-allow.md, packages/react-centra-checkout/src/ApiClient.ts
Tried to extend the `ApiClient` class, while i receieved a `TS2340`
error from TypeScript. Defining the `request` property as a method (and
not a function) resolves that error.
Related sources for solution:
- https://stackoverflow.com/questions/55422250/typescript-cannot-call-super-method-on-child-class
- https://codereviewvideos.com/how-i-fixed-ts2340-only-public-and-protected-methods-of-the-base-class-are-accessible-via-the-super-keyword/
=> fix(react-centra-checkout): unable to call method on base class

.changeset/young-stars-divide.md, packages/create-app/template-docs/.gitignore
`storybook-static` is considered a dist / build directory, outputted by
the `build` script. Think we can `gitignore` it.
=> fix(create-app): `storybook-static` output folder is not ignored
